// Fetch the HUD's two faces from Google Fonts and SELF-HOST them.
//
// Licence: both are SIL Open Font License 1.1. Commercial use permitted,
// bundling and redistribution permitted, the licence text must travel with
// the fonts, and the fonts may not be sold on their own. The licence is
// written to public/fonts/OFL.txt beside them.
//
// The @font-face rules keep the families' REAL names ("Rajdhani", "Barlow
// Condensed") rather than inventing an alias, so the stylesheet is a drop-in
// for the Google link that used to be in index.html: nothing else in the
// codebase has to know the fonts moved.
//
// Self-hosted and not linked, for three reasons that all bit this project
// before. The game is served from one small box behind Caddy and should make
// no third-party request at all: a blocked or slow fonts.googleapis.com used
// to hold the first frame. It has to work offline, because the range is
// played on a laptop on a plane. And a font that arrives late reflows the
// HUD mid-fight, which is worse than a font that never arrives.
//
// Run: npm run fonts
// Downloaded files are gitignored; this script is the source of truth.
import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = resolve(fileURLToPath(new URL(".", import.meta.url)), "..", "public", "fonts");

/**
 * The pair. A condensed face for numbers and labels that must fit a narrow
 * box (ammo counts, damage numbers, the ring timer, place names) and a
 * neutral face for anything the player reads as a sentence (menus, settings,
 * the recap). Only the weights the HUD uses, because every extra weight is
 * another file on the wire.
 */
const FACES: Array<{ family: string; weights: number[]; as: string; note: string }> = [
  { family: "Barlow Condensed", weights: [500, 600, 700], as: "display", note: "ammo, damage numbers, timers, place names" },
  // 700 is not optional: index.html sets it on the brand, the tab headings,
  // the stat cards and the welcome, and src/game/course.ts asks the browser
  // for '700 40px "Rajdhani"' by name. Without the real weight the browser
  // synthesises a fake bold, which is heavier and blurrier than the face.
  { family: "Rajdhani", weights: [500, 600, 700], as: "ui", note: "menus, settings, the recap and the boards" },
];

/**
 * Google serves woff2 only to a user agent it believes supports it. With
 * node's default agent it returns the ancient TrueType URLs instead, which
 * are four times the size, so the agent is not decoration.
 */
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

const OFL_TXT = "https://raw.githubusercontent.com/google/fonts/main/ofl/barlowcondensed/OFL.txt";

async function get(url: string, headers: Record<string, string> = {}): Promise<Buffer> {
  const r = await fetch(url, { redirect: "follow", headers });
  if (!r.ok) throw new Error(`HTTP ${r.status} for ${url}`);
  return Buffer.from(await r.arrayBuffer());
}

async function main(): Promise<void> {
  mkdirSync(OUT, { recursive: true });
  const css: string[] = [
    "/* Self-hosted from Google Fonts by tools/fetch-fonts.ts (SIL OFL 1.1).",
    "   Regenerated by `npm run fonts`; see public/fonts/ATTRIBUTION.md. */",
    "",
  ];
  const credits: string[] = [
    "# Font attribution",
    "",
    "Both faces are from Google Fonts under the **SIL Open Font License 1.1**",
    "(`OFL.txt` in this folder). Commercial use, bundling and redistribution are",
    "permitted; the licence travels with the files; the fonts are not sold alone.",
    "",
    "| File | Family | Used for |",
    "|---|---|---|",
  ];
  let bytes = 0;

  for (const face of FACES) {
    const q = `family=${face.family.replace(/ /g, "+")}:wght@${face.weights.join(";")}&display=block`;
    process.stdout.write(`  ${face.family} ... `);
    const sheet = (await get(`https://fonts.googleapis.com/css2?${q}`, { "user-agent": UA })).toString("utf8");
    // one @font-face block per weight, each with a woff2 url and a unicode-range
    const blocks = sheet.split("@font-face").slice(1);
    let n = 0;
    for (const block of blocks) {
      const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
      const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
      const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
      if (!url || !weight) continue;
      // latin only: the HUD has no other script, and the extra subsets are
      // most of the bytes
      if (range && !/U\+0000-00FF/.test(range)) continue;
      const file = `${face.as}-${weight}.woff2`;
      const data = await get(url, { "user-agent": UA });
      writeFileSync(join(OUT, file), data);
      bytes += data.length;
      n++;
      css.push(
        "@font-face {",
        `  font-family: "${face.family}";`,
        `  font-weight: ${weight};`,
        "  font-style: normal;",
        "  font-display: block;",
        `  src: url("${file}") format("woff2");`,
        "}",
        ""
      );
      credits.push(`| \`${file}\` | ${face.family} ${weight} (OFL 1.1) | ${face.note} |`);
    }
    if (!n) throw new Error(`no woff2 faces found for ${face.family}`);
    console.log(`${n} weights`);
  }

  writeFileSync(join(OUT, "fonts.css"), css.join("\n"));
  writeFileSync(join(OUT, "OFL.txt"), await get(OFL_TXT));
  credits.push("", "Re-fetch with `npm run fonts` (tools/fetch-fonts.ts); the files are gitignored.", "");
  writeFileSync(join(OUT, "ATTRIBUTION.md"), credits.join("\n"));
  console.log(`\n${(bytes / 1024).toFixed(0)} KB in ${OUT}`);
}

void main();
